//
//  Data.swift
//  DNApp
//
//  Created by KingMartin on 15/10/19.
//  Copyright © 2015年 Meng To. All rights reserved.
//

import UIKit

    var data: [[String:AnyObject]] = [
        [
            "id": 57722,
            "title": "Show DN: Simple Icons",
            "comment": "",
            "comment_html": "",
            "comment_count": 15,
            "vote_count": 21,
            "created_at": "2015-10-19T10:45:28Z",
            "pinned_at": "",
            "url": "https://www.designernews.co/click/stories/57722",
            "site_url": "https://api.designernews.co/stories/57722-show-dn-simple-icons",
            "user_id": 1347,
            "user_display_name": "Dan L.",
            "user_portrait_url": "https://designer-news-production.s3.amazonaws.com/rendered_portraits/1347/original/portrait-2015-09-20_10_00_59__0000-134720150920-3-88y6sc.png?AWSAccessKeyId=AKIAIBH3R762QIPXF4IQ&Expires=1476828214&Signature=ZFLIjdHw7rzUMSqVS2%2FZKMhTHq0%3D",
            "hostname": "simpleicons.org",
            "user_url": "http://www.designernews.co/users/1347/dan-leech",
            "badge": "show",
            "user_job": "Software Designer",
            "sponsored": false,
            
            "comments": [
                [
                    "id": 181569,
                    "body": "I don't understand what the use-case for this is.",
                    "body_html": "<p>I don&#39;t understand what the use-case for this is.</p>\n",
                    "created_at": "2015-10-19T11:14:42Z",
                    "depth": 0,
                    "vote_count": 0,
                    "url": "https://api.designernews.co/comments/181569",
                    "user_url": "http://www.designernews.co/users/4359/rami-james",
                    "user_id": 4359,
                    "user_display_name": "Rami J.",
                    "user_portrait_url": "https://designer-news-production.s3.amazonaws.com/rendered_portraits/4359/original/portrait-2015-05-30_03_31_40__0000-435920150530-3-1i19r36.png?AWSAccessKeyId=AKIAIBH3R762QIPXF4IQ&Expires=1476825089&Signature=Z308mMFryxNodG%2Bx0NkmfrEgim4%3D",
                    "user_job": "http://www.letstalkdesign.co",
                ],
                [
                    "id": 181573,
                    "body": "They're icons. You can use them in your design work. ",
                    "body_html": "<p>They&#39;re icons. You can use them in your design work. </p>\n",
                    "created_at": "2015-10-19T12:02:07Z",
                    "depth": 1,
                    "vote_count": 2,
                    "url": "https://api.designernews.co/comments/181573",
                    "user_url": "http://www.designernews.co/users/3084/james-young",
                    "user_id": 3084,
                    "user_display_name": "James Y.",
                    "user_portrait_url": "https://designer-news-production.s3.amazonaws.com/rendered_portraits/3084/original/portrait-2015-10-16_05_14_59__0000-308420151016-3-o7dto3.png?AWSAccessKeyId=AKIAIBH3R762QIPXF4IQ&Expires=1476825089&Signature=Aipawtl2vS88Jy5oP11BWfCwjhQ%3D",
                    "user_job": "Creative Director @Offroadcode",
                    "comments": []
                ]
            ]
        ],
        [
            "id": 57715,
            "title": "jQuery Recipes Your Mom Should Know",
            "comment": "",
            "comment_html": "",
            "comment_count": 3,
            "vote_count": 15,
            "created_at": "2015-10-19T07:46:13Z",
            "pinned_at": "",
            "url": "https://www.designernews.co/click/stories/57715",
            "site_url": "https://www.designernews.co/stories/57715-jquery-recipes-your-mom-should-know",
            "user_id": 15515,
            "user_display_name": "Gilles B.",
            "user_portrait_url": "https://designer-news-production.s3.amazonaws.com/rendered_portraits/15515/original/portrait-2015-05-30_04_18_26__0000-1551520150530-3-s3zsrh.png?AWSAccessKeyId=AKIAIBH3R762QIPXF4IQ&Expires=1476828682&Signature=879W%2FQF%2B5t%2FTlFEUmoFIGfoKx2M%3D",
            "hostname": "github.com",
            "user_url": "http://www.designernews.co/users/15515/gilles-bertaux",
            "badge": "css",
            "user_job": "Freelance Product Designer",
            "sponsored": false,
        ],
        ["id": 57723,
        "title": "Introducing Bootstrap Studio A powerful web design tool for creating responsive websites using the Bootstrap framework.",
        "comment": "",
        "comment_html": "",
        "comment_count": 1,
        "vote_count": 9,
        "created_at": "",
        "pinned_at": "",
        "url": "https://www.designernews.co/click/stories/57723",
        "site_url": "https://api.designernews.co/stories/57723-introducing-bootstrap-studio-a-powerful-web-design-tool-for-creating-responsive-websites-using-the-bootstrap-framework",
        "user_id": 28252,
        "user_display_name": "Anselm U.",
        "user_portrait_url": "https://designer-news-production.s3.amazonaws.com/rendered_portraits/28252/original/portrait-2015-07-27_08_29_12__0000-2825220150727-3-ueso99.png?AWSAccessKeyId=AKIAIBH3R762QIPXF4IQ&Expires=1476825584&Signature=DzmSnyyRV20zB3GzkjSiZQtmi9A%3D",
        "hostname": "bootstrapstudio.io",
        "user_url": "http://www.designernews.co/users/28252/anselm-urban",
        "badge": "ask",
        "user_job": "Student, web designer and dev @ URBAN|design and https://html5sit.es/",
        "sponsored": false,],
        [
            "id": 57727,
            "title": "Featured: With Framer, You Can Import Your Visual Designs and Bring Them to Life. Start Prototyping Now.",
            "comment": "",
            "comment_html": "",
            "comment_count": 0,
            "vote_count": 15,
            "created_at": "2015-10-19T13:16:57Z",
            "pinned_at": "",
            "url": "https://www.designernews.co/click/stories/57727",
            "site_url": "https://api.designernews.co/stories/57727-featured-with-framer-you-can-import-your-visual-designs-and-bring-them-to-life-start-prototyping-now",
            "user_id": 1709,
            "user_display_name": "Maxwell L.",
            "user_portrait_url": "https://designer-news-production.s3.amazonaws.com/rendered_portraits/1709/original/portrait-2015-07-06_17_57_13__0000-170920150706-3-y3p3nr.png?AWSAccessKeyId=AKIAIBH3R762QIPXF4IQ&Expires=1476827453&Signature=3pxEwosiEjp8Wg227egJueTzTFQ%3D",
            "hostname": "framerjs.com",
            "user_url": "http://www.designernews.co/users/1709/maxwell-lind",
            "badge": "ama",
            "user_job": "Community Manager at Designer News",
            "sponsored": true,
        ],
        ["id": 57714,
            "title": "Protein - UI components sync service for any stack or platform. Landing update.",
            "comment": "",
            "comment_html": "",
            "comment_count": 3,
            "vote_count": 5,
            "created_at": "2015-10-19T07:31:07Z",
            "pinned_at": "",
            "url": "https://www.designernews.co/click/stories/57714",
            "site_url": "https://www.designernews.co/stories/57714-protein--ui-components-sync-service-for-any-stack-or-platform-landing-update",
            "user_id": 27652,
            "user_display_name": "Anton W.",
            "user_portrait_url": "",
            "hostname": "theprotein.io",
            "user_url": "http://www.designernews.co/users/27652/anton-winogradov",
            "badge": "sitedesign",
            "user_job": "The Protein Corp.",
            "sponsored": false,
        ],
        [
            "id": 57713,
            "title": "Geniuses we love – Dana Tanamachi",
            "comment": "",
            "comment_html": "",
            "comment_count": 0,
            "vote_count": 6,
            "created_at": "2015-10-19T07:29:21Z",
            "pinned_at": "",
            "url": "https://www.designernews.co/click/stories/57713",
            "site_url": "https://www.designernews.co/stories/57713-geniuses-we-love--dana-tanamachi",
            "user_id": 7742,
            "user_display_name": "eyal z.",
            "user_portrait_url": "https://designer-news-production.s3.amazonaws.com/rendered_portraits/7742/original/portrait-2015-05-30_03_45_45__0000-774220150530-3-dt3bok.png?AWSAccessKeyId=AKIAIBH3R762QIPXF4IQ&Expires=1476822288&Signature=SWe9STv31bZqJwZHbIusbIT8xjo%3D",
            "hostname": "muz.li",
            "user_url": "http://www.designernews.co/users/7742/eyal-zuri",
            "badge": "sketch",
            "user_job": "ux/ui designer",
            "sponsored": false,
        ],
        [
            "id": 57713,
            "title": "Geniuses we love – Dana Tanamachi",
            "comment": "",
            "comment_html": "",
            "comment_count": 0,
            "vote_count": 6,
            "created_at": "2015-10-19T07:29:21Z",
            "pinned_at": "",
            "url": "https://www.designernews.co/click/stories/57713",
            "site_url": "https://www.designernews.co/stories/57713-geniuses-we-love--dana-tanamachi",
            "user_id": 7742,
            "user_display_name": "eyal z.",
            "user_portrait_url": "https://designer-news-production.s3.amazonaws.com/rendered_portraits/7742/original/portrait-2015-05-30_03_45_45__0000-774220150530-3-dt3bok.png?AWSAccessKeyId=AKIAIBH3R762QIPXF4IQ&Expires=1476822288&Signature=SWe9STv31bZqJwZHbIusbIT8xjo%3D",
            "hostname": "muz.li",
            "user_url": "http://www.designernews.co/users/7742/eyal-zuri",
            "badge": "sketch",
            "user_job": "ux/ui designer",
            "sponsored": false,
        ],
        [
            "id": 57713,
            "title": "Geniuses we love – Dana Tanamachi",
            "comment": "",
            "comment_html": "",
            "comment_count": 0,
            "vote_count": 6,
            "created_at": "2015-10-19T07:29:21Z",
            "pinned_at": "",
            "url": "https://www.designernews.co/click/stories/57713",
            "site_url": "https://www.designernews.co/stories/57713-geniuses-we-love--dana-tanamachi",
            "user_id": 7742,
            "user_display_name": "eyal z.",
            "user_portrait_url": "https://designer-news-production.s3.amazonaws.com/rendered_portraits/7742/original/portrait-2015-05-30_03_45_45__0000-774220150530-3-dt3bok.png?AWSAccessKeyId=AKIAIBH3R762QIPXF4IQ&Expires=1476822288&Signature=SWe9STv31bZqJwZHbIusbIT8xjo%3D",
            "hostname": "muz.li",
            "user_url": "http://www.designernews.co/users/7742/eyal-zuri",
            "badge": "sketch",
            "user_job": "ux/ui designer",
            "sponsored": false,
        ],
        [
            "id": 57713,
            "title": "Geniuses we love – Dana Tanamachi",
            "comment": "",
            "comment_html": "",
            "comment_count": 0,
            "vote_count": 6,
            "created_at": "2015-10-19T07:29:21Z",
            "pinned_at": "",
            "url": "https://www.designernews.co/click/stories/57713",
            "site_url": "https://www.designernews.co/stories/57713-geniuses-we-love--dana-tanamachi",
            "user_id": 7742,
            "user_display_name": "eyal z.",
            "user_portrait_url": "https://designer-news-production.s3.amazonaws.com/rendered_portraits/7742/original/portrait-2015-05-30_03_45_45__0000-774220150530-3-dt3bok.png?AWSAccessKeyId=AKIAIBH3R762QIPXF4IQ&Expires=1476822288&Signature=SWe9STv31bZqJwZHbIusbIT8xjo%3D",
            "hostname": "muz.li",
            "user_url": "http://www.designernews.co/users/7742/eyal-zuri",
            "badge": "sketch",
            "user_job": "ux/ui designer",
            "sponsored": false,
        ]



        
        
    ]

